EBS_GP3_PER_GB_MONTH = 0.08
EBS_GP2_PER_GB_MONTH = 0.10
EBS_DEFAULT_SIZE_GB = 20

EIP_UNATTACHED_PER_MONTH = 3.65

EC2_DEFAULT_WASTE_PER_MONTH = 7.59

UNTAGGED_WASTE_PER_MONTH = 0.0

REQUIRED_TAGS = ["Project", "Environment", "Owner"]